# Generated by Django 6.0.7 on 2026-08-26 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bank_statements/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.CharField(default='2026-2027', max_length=9)),
                ('status', models.CharField(choices=[('PENDING', 'À traiter'), ('PARTIAL', 'Partiellement rapproché'), ('PROCESSED', 'Traité'), ('ERROR', 'Erreur')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='accounts.universitybankaccount')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements_imported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.bankstatement'),
        ),
    ]
