# Generated by Django 6.0.7 on 2026-08-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bankstatement_banktransaction_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='academic_year',
            field=models.CharField(max_length=9),
        ),
    ]
