# Generated by Django 6.0.7 on 2026-07-31 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_banktransaction_paymentclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentclaim',
            name='bank_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim', to='accounts.banktransaction'),
        ),
    ]
